dist: trusty

language: python
python:
  - "2.7"

env:
  fast_finish: true

install:
  - pip install -e .
  - pip install pep8

script:
  # - nosetests -v
  - cd studio/tests && python local_worker_test.py
  - pep8 --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
