dist: trusty

language: python
python:
  - "2.7"

env:
  fast_finish: true

install:
  - pip install -e .

script:
  - nosetests --processes=4 --process-timeout=600
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
