dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

env:
  fast_finish: true

install:
  - pip install -e .
  - pip install pep8
  - echo $GOOGLE_CREDENTIALS_ENCODED | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS

script:
  # - nosetests -v 
  - cd studio/tests && python artifact_store_test.py
  - pep8 --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
