dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

env:
  fast_finish: true

sudo: required
services: 
    - docker

install:
  - pip install -e .
  - pip install pep8
  - pip install -r extra_test_requirements.txt
  - docker pull peterzhokhoff/studioml

  - 'if [ -n "$GOOGLE_CREDENTIALS_ENCODED" ]; then echo "$GOOGLE_CREDENTIALS_ENCODED" | base64 --decode > ./credentials.json && export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json; fi'

script:
  - echo $GOOGLE_APPLICATION_CREDENTIALS
  - cd studio/tests && python -m unittest -q remote_worker_test.RemoteWorkerTest.test_remote_worker
  # - cd studio/tests && nosetests -v remote_worker_test  --processes=16 --process-timeout=590
  - pep8 --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
