dist: trusty

language: python
python:
  - "3.6"

env:
  fast_finish: true

install:
  - pip install -e .
  - pip install pep8

script:
  - nosetests
  - pep8 --show-source .
  - python setup.py sdist
  - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages
deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
