dist: trusty

language: python
python:
  - "2.7"

env:
  fast_finish: true

install:
  - pip install .

script:
  - python studio/tests/http_provider_test.py
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
