database:
    type: gs
    bucket: "studioml-meta" 
    projectId: "studio-ed756"

    authentication:
      type: none

storage:
    type: gcloud
    bucket: studio-ed756.appspot.com

   
verbose: debug


