runtime: python
# api_verison: 1
env: flex
threadsafe: false

runtime_config:
    python_version: 3

handlers:
    - url: /.*
      script: studio.app
 
libraries:
    - name: ssl
      version: latest
