database: 
    type: FireBase

    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    projectId: studio-ed756
    messagingSenderId: 81790704397

    authDomain: "{}.firebaseapp.com"
    databaseURL: "https://{}.firebaseio.com"
    storageBucket: "{}.appspot.com"

    # guest: true

    # use_email_auth: true
                                                                    
saveWorkspaceFrequency: 1 #how often is workspace being saved (minutes)
verbose: error

cloud:
    type: google
    zone: us-central1-f

    cpus: 2
    ram:  4g
    hdd:  10g
    gpus: 0

