database: 
    type: FireBase
    url: https://studio-ed756.firebaseio.com/
    secret: 3NE3ONN9CJgjqhC5Ijlr9DTNXmmyladvKhD2AbLk

log:
    name: output.log
    mode: w

saveWorkspaceFrequency: 1 #how often is workspace being saved (minutes)
