database: 
    type: FireBase

    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    projectId: studio-ed756
    messagingSenderId: 81790704397

    authDomain: "{}.firebaseapp.com"
    databaseURL: "https://{}.firebaseio.com"
    storageBucket: "{}.appspot.com"

    # guest: true

    # use_email_auth: true
                                                                    
log:
    name: output.log

saveWorkspaceFrequency: 1 #how often is workspace being saved (minutes)

