database:
    type: gs
    apiKey: AIzaSyBBXZN-irWpOcdgDQFSTqLMY8r7VmnEwas
    authDomain: "{}.firebaseapp.com"
    bucket: "studioml-sentient-meta"
    projectId: "studio-sentient"
    
    guest: true
    use_email_auth: false



storage:
    type: s3
    bucket: "studioml-artifacts-west"

   
saveWorkspaceFrequencyMinutes: 1
verbose: debug


